CREATE TABLE `inventories` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `ItemUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `StockQuantity` decimal(18,3) NOT NULL,
  `AllowsDecimalQuantities` tinyint(1) NOT NULL,
  `UnitType` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `CreatedBy` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UpdatedBy` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT '1',
  `Comment` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `Reason` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IsUserAdjusted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `AK_Inventories_Uuid` (`Uuid`),
  UNIQUE KEY `IX_Inventories_ItemUuid` (`ItemUuid`),
  KEY `IX_Inventories_CreatedBy` (`CreatedBy`),
  KEY `IX_Inventories_UpdatedBy` (`UpdatedBy`),
  CONSTRAINT `FK_Inventories_Items_ItemUuid` FOREIGN KEY (`ItemUuid`) REFERENCES `items` (`Uuid`) ON DELETE CASCADE,
  CONSTRAINT `FK_Inventories_Users_CreatedBy` FOREIGN KEY (`CreatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_Inventories_Users_UpdatedBy` FOREIGN KEY (`UpdatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2894 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci