CREATE TABLE `itemexpiries` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `ItemsId` int NOT NULL,
  `ItemsSubId` int NOT NULL,
  `ItemUuid` varchar(36) NOT NULL,
  `ExpDate` date NOT NULL,
  `NotifyBeforeDays` int NOT NULL DEFAULT '0',
  `Uuid` varchar(36) NOT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `CreatedBy` varchar(36) DEFAULT NULL,
  `UpdatedBy` varchar(36) DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`Id`),
  KEY `IX_ItemExpiries_Item` (`ItemsId`,`ItemsSubId`),
  KEY `FK_ItemExpiries_Users_CreatedBy` (`CreatedBy`),
  KEY `FK_ItemExpiries_Users_UpdatedBy` (`UpdatedBy`),
  CONSTRAINT `FK_ItemExpiries_Items` FOREIGN KEY (`ItemsId`, `ItemsSubId`) REFERENCES `items` (`Id`, `SubId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ItemExpiries_Users_CreatedBy` FOREIGN KEY (`CreatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_ItemExpiries_Users_UpdatedBy` FOREIGN KEY (`UpdatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=945 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci