CREATE TABLE `itemsuppliers` (
  `SuppliersId` int NOT NULL,
  `ItemsId` int NOT NULL,
  `ItemsSubId` int NOT NULL,
  `Uuid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `CreatedBy` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UpdatedBy` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`SuppliersId`,`ItemsId`,`ItemsSubId`),
  UNIQUE KEY `AK_ItemSuppliers_Uuid` (`Uuid`),
  KEY `IX_ItemSuppliers_ItemsId_ItemsSubId` (`ItemsId`,`ItemsSubId`),
  KEY `FK_ItemSuppliers_Users_CreatedBy` (`CreatedBy`),
  KEY `FK_ItemSuppliers_Users_UpdatedBy` (`UpdatedBy`),
  CONSTRAINT `FK_ItemSuppliers_Items_ItemsId_ItemsSubId` FOREIGN KEY (`ItemsId`, `ItemsSubId`) REFERENCES `items` (`Id`, `SubId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ItemSuppliers_Suppliers_SuppliersId` FOREIGN KEY (`SuppliersId`) REFERENCES `suppliers` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ItemSuppliers_Users_CreatedBy` FOREIGN KEY (`CreatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_ItemSuppliers_Users_UpdatedBy` FOREIGN KEY (`UpdatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci