CREATE TABLE `itemprices` (
  `ItemsId` int NOT NULL,
  `ItemsSubId` int NOT NULL,
  `ItemUuid` varchar(36) NOT NULL,
  `BuyingPrice` decimal(18,2) NOT NULL DEFAULT '0.00',
  `MarkedPrice` decimal(18,2) NOT NULL DEFAULT '0.00',
  `RetailPrice` decimal(18,2) NOT NULL DEFAULT '0.00',
  `WholesalePrice` decimal(18,2) NOT NULL DEFAULT '0.00',
  `RetailDiscountRatio` decimal(5,2) NOT NULL DEFAULT '0.00',
  `WholesaleDiscountRatio` decimal(5,2) NOT NULL DEFAULT '0.00',
  `Uuid` varchar(36) NOT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `CreatedBy` varchar(36) DEFAULT NULL,
  `UpdatedBy` varchar(36) DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ItemsId`,`ItemsSubId`),
  UNIQUE KEY `UX_ItemPrices_ItemUuid` (`ItemUuid`),
  KEY `FK_ItemPrices_Users_CreatedBy` (`CreatedBy`),
  KEY `FK_ItemPrices_Users_UpdatedBy` (`UpdatedBy`),
  CONSTRAINT `FK_ItemPrices_Items` FOREIGN KEY (`ItemsId`, `ItemsSubId`) REFERENCES `items` (`Id`, `SubId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ItemPrices_Users_CreatedBy` FOREIGN KEY (`CreatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_ItemPrices_Users_UpdatedBy` FOREIGN KEY (`UpdatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci