CREATE TABLE `orderitems` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `OrderId` int NOT NULL,
  `OriginalItemUuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `AllowsDecimalQuantities` tinyint(1) NOT NULL,
  `PrintName` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `Quantity` decimal(18,3) NOT NULL,
  `PriceAtSale` decimal(18,2) NOT NULL,
  `MarkedPriceAtSale` decimal(18,2) NOT NULL,
  `CostAtSale` decimal(18,2) NOT NULL,
  `LineTotal` decimal(18,2) NOT NULL,
  `IsReturnItem` tinyint(1) NOT NULL DEFAULT '0',
  `ReturnedOrderItemUuid` varchar(36) DEFAULT NULL,
  `Description` varchar(500) DEFAULT NULL,
  `Uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `CreatedBy` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UpdatedBy` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `AK_OrderItems_Uuid` (`Uuid`),
  KEY `IX_OrderItems_OrderId` (`OrderId`),
  KEY `IX_OrderItems_OriginalItemUuid` (`OriginalItemUuid`),
  KEY `FK_OrderItems_Users_CreatedBy` (`CreatedBy`),
  KEY `FK_OrderItems_Users_UpdatedBy` (`UpdatedBy`),
  CONSTRAINT `FK_OrderItems_Items_OriginalItemUuid` FOREIGN KEY (`OriginalItemUuid`) REFERENCES `items` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_OrderItems_Orders_OrderId` FOREIGN KEY (`OrderId`) REFERENCES `orders` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_OrderItems_Users_CreatedBy` FOREIGN KEY (`CreatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_OrderItems_Users_UpdatedBy` FOREIGN KEY (`UpdatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=577 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci