CREATE TABLE `reporttemplatesqltemplates` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `ReportTemplateId` int NOT NULL,
  `SqlTemplateId` int NOT NULL,
  `Uuid` varchar(36) NOT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `CreatedBy` varchar(36) DEFAULT NULL,
  `UpdatedBy` varchar(36) DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `AK_ReportTemplateSqlTemplates_Uuid` (`Uuid`),
  KEY `IX_ReportTemplateSqlTemplates_ReportTemplateId` (`ReportTemplateId`),
  KEY `IX_ReportTemplateSqlTemplates_SqlTemplateId` (`SqlTemplateId`),
  KEY `IX_ReportTemplateSqlTemplates_CreatedBy` (`CreatedBy`),
  KEY `IX_ReportTemplateSqlTemplates_UpdatedBy` (`UpdatedBy`),
  CONSTRAINT `FK_ReportTemplateSqlTemplates_ReportTemplates_ReportTemplateId` FOREIGN KEY (`ReportTemplateId`) REFERENCES `reporttemplates` (`Id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ReportTemplateSqlTemplates_Users_CreatedBy` FOREIGN KEY (`CreatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_ReportTemplateSqlTemplates_Users_UpdatedBy` FOREIGN KEY (`UpdatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_SqlTemplate_Id` FOREIGN KEY (`SqlTemplateId`) REFERENCES `sqltemplates` (`Id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=127 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci