CREATE TABLE `reporttemplates` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `ReportName` varchar(255) NOT NULL,
  `Description` varchar(1000) DEFAULT NULL,
  `HtmlContent` longtext NOT NULL,
  `ParametersJson` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `SqlPlaceholderMappingsJson` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `Uuid` varchar(36) NOT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `CreatedBy` varchar(36) DEFAULT NULL,
  `UpdatedBy` varchar(36) DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Uuid` (`Uuid`),
  UNIQUE KEY `ReportName` (`ReportName`),
  KEY `reporttemplates_ibfk_1` (`CreatedBy`),
  KEY `reporttemplates_ibfk_2` (`UpdatedBy`),
  CONSTRAINT `reporttemplates_ibfk_1` FOREIGN KEY (`CreatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `reporttemplates_ibfk_2` FOREIGN KEY (`UpdatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci