CREATE TABLE `sqltemplates` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `TemplateName` varchar(255) NOT NULL,
  `Description` varchar(1000) DEFAULT NULL,
  `SqlQuery` longtext NOT NULL,
  `PlaceholdersJson` longtext,
  `SelectValuesJson` longtext,
  `Uuid` varchar(36) NOT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `CreatedBy` varchar(36) DEFAULT NULL,
  `UpdatedAt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `UpdatedBy` varchar(36) DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Uuid` (`Uuid`),
  UNIQUE KEY `TemplateName` (`TemplateName`),
  KEY `CreatedBy` (`CreatedBy`),
  KEY `UpdatedBy` (`UpdatedBy`),
  CONSTRAINT `sqltemplates_ibfk_1` FOREIGN KEY (`CreatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL,
  CONSTRAINT `sqltemplates_ibfk_2` FOREIGN KEY (`UpdatedBy`) REFERENCES `users` (`Uuid`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci