CREATE TABLE `tbl_orders` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `OrderNumber` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `MainStatus` varchar(50) NOT NULL,
  `SubStatus` varchar(50) DEFAULT NULL,
  `PaymentMethod` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SaleType` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `ItemCount` int NOT NULL,
  `GrossAmount` decimal(18,2) NOT NULL,
  `TotalDiscount` decimal(18,2) NOT NULL,
  `NetAmount` decimal(18,2) NOT NULL,
  `TotalCost` decimal(18,2) NOT NULL,
  `AmountPaid` decimal(18,2) NOT NULL,
  `Balance` decimal(18,2) NOT NULL,
  `CashierId` int DEFAULT NULL,
  `CustomerId` int DEFAULT NULL,
  `Description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `Uuid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `CreatedBy` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UpdatedBy` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `AK_tbl_orders_Uuid` (`Uuid`),
  UNIQUE KEY `IX_tbl_orders_OrderNumber` (`OrderNumber`),
  KEY `IX_tbl_orders_CashierId` (`CashierId`),
  KEY `IX_tbl_orders_CustomerId` (`CustomerId`),
  KEY `FK_tbl_orders_tbl_users_CreatedBy` (`CreatedBy`),
  KEY `FK_tbl_orders_tbl_users_UpdatedBy` (`UpdatedBy`),
  CONSTRAINT `FK_tbl_orders_tbl_customers_CustomerId` FOREIGN KEY (`CustomerId`) REFERENCES `tbl_customers` (`Id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_tbl_orders_tbl_users_CashierId` FOREIGN KEY (`CashierId`) REFERENCES `tbl_users` (`Id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_tbl_orders_tbl_users_CreatedBy` FOREIGN KEY (`CreatedBy`) REFERENCES `tbl_users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_tbl_orders_tbl_users_UpdatedBy` FOREIGN KEY (`UpdatedBy`) REFERENCES `tbl_users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
