CREATE TABLE `tbl_report_templates` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `ReportName` varchar(255) NOT NULL,
  `Description` varchar(1000) DEFAULT NULL,
  `HtmlContent` longtext NOT NULL,
  `ParametersJson` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `SqlPlaceholderMappingsJson` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `Uuid` varchar(36) NOT NULL,
  `CreatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdatedAt` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `CreatedBy` varchar(36) DEFAULT NULL,
  `UpdatedBy` varchar(36) DEFAULT NULL,
  `IsActive` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `AK_tbl_report_templates_Uuid` (`Uuid`),
  UNIQUE KEY `IX_tbl_report_templates_ReportName` (`ReportName`),
  KEY `FK_tbl_report_templates_tbl_users_CreatedBy` (`CreatedBy`),
  KEY `FK_tbl_report_templates_tbl_users_UpdatedBy` (`UpdatedBy`),
  CONSTRAINT `FK_tbl_report_templates_tbl_users_CreatedBy` FOREIGN KEY (`CreatedBy`) REFERENCES `tbl_users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_tbl_report_templates_tbl_users_UpdatedBy` FOREIGN KEY (`UpdatedBy`) REFERENCES `tbl_users` (`Uuid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
